import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
//import deved from "../public/dev-ed-wave.png";
import yuv from "../public/y.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Yuvraj_Singh_Toriya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">YuvrajSingh</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1R3qbmpyJw9CuzP7Vk7CeK0C-UbvtrCKP/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Yuvraj Singh
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Enginnering Student.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Finding creative solutions to problems is something I have always
              enjoyed. As a kid I loved tinkering with things that were broken,
              figuring out how they worked and fixing them again. When I
              finished high school, I knew exactly what I wanted my career to
              be.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/INDYuvraj_Singh">
                <AiFillTwitterCircle />
              </a>
              <a href="https://www.linkedin.com/in/yuvraj-singh-toriya-12975422a/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/yuvraj625">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image
                src={deved}
                alt="avatar picture"
                layout="fill"
                objectFit="cover"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About Me!</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I will finish up my degree at [National institute of technology,
              Rourkela], where I’m learning how to apply critical thinking and
              problem-solving strategies to today’s complex problems.
              <br></br>
              Worked with <span className="text-teal-500">startups </span>and
              <span className="text-teal-500"> collaborated </span>
              with talanted people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including website design,
              Equity Trading, helped local businesses to scale up.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={design}
                alt="avatar picture"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Education Background
              </h3>
              <p className="py-2">
                National Institute of Technology Rourkela (2021-2025)
              </p>
              <h4 className="py-4 text-teal-600">Contact Me here !</h4>
              <p className="text-gray-800 py-1"></p>
              <p className="text-gray-800 py-1">yuvrajsinghtoriya@gmail.com</p>
              <a
                className="text-gray-800 py-1"
                href="https://www.linkedin.com/in/yuvraj-singh-toriya-12975422a"
              >
                Linkedin
              </a>
              <p className="text-gray-800 py-1"></p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} alt="avatar picture" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Relevent Skills
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">React JS</p>
              <p className="text-gray-800 py-1">Express Js</p>
              <p className="text-gray-800 py-1">Node Js</p>
              <p className="text-gray-800 py-1">Mongo DB</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image
                src={consulting}
                alt="avatar picture"
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                EXTRA CURRICULAR
              </h3>
              <p className="py-2">
                Are you interested in creating something or want to explore
                together?
              </p>
              <h4 className="py-4 text-teal-600">Volunteering</h4>
              <p className="text-gray-800 py-1">
                2021‐2022 Volunteer, National Service Scheme NSS
              </p>
              <p className="text-gray-800 py-1">Equity Trading</p>
              <p className="text-gray-800 py-1">Da Vinci Resolve</p>
              <p className="text-gray-800 py-1"></p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I have added valuable content for
              <span className="text-teal-500"> Local Businesses </span>
              and for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and Enginnering.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt="avatar picture"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt="avatar picture"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt="avatar picture"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt="avatar picture"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt="avatar picture"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt="avatar picture"
              />
            </div>
          </div>
          <a
            className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
            href="https://drive.google.com/file/d/1R3qbmpyJw9CuzP7Vk7CeK0C-UbvtrCKP/view?usp=sharing"
          >
            Download Resume !
          </a>
        </section>
      </main>
    </div>
  );
}
